site_name: TWIL
site_description: This Week I Learned, TWIL
site_url: https://twil.weekwith.me
theme:
  name: material
  custom_dir: overrides
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode      
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - header.autohide      
    - navigation.tabs
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
repo_name: GitHub
repo_url: https://github.com/week-with-me/TWIL
edit_uri: ''

plugins:
- search
- markdownextradata:
    data: data 

markdown_extensions:
- meta
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed  

nav:
- About TWIL:
  - index.md
  - writing-guideline/index.md
  - guideline/index.md
- 1기:
  - 박지연:
    - 1기/박지연/2021-07-11-TypeScript의-기초.md
    - 1기/박지연/2021-07-18-javascript-변수-데이터-타입.md
  - 성승익:
    - 1기/성승익/2021-07-11-Ruby-on-rails란-무엇일까.md
    - 1기/성승익/2021-07-18-Rails로-게시판을-만들어보자-컨트롤러.md
    - 1기/성승익/2021-07-25-Rails로-게시판을-만들어보자-모델-1.md
    - 1기/성승익/2021-08-01-Rails로-게시판을-만들어보자-모델-2.md
  - 신태범:
    - 1기/신태범/2021-07-11-CS-하면-생기는-일.md
    - 1기/신태범/2021-07-18-CS-HTTP-1-vs-HTTP2.md
    - 1기/신태범/2021-07-25-CS-SQL-vs-NOSQL.md
  - 이동근:
    - 1기/이동근/2021-07-11-CS-면접-준비-및-자기소개.md
    - 1기/이동근/2021-07-18-자바스크립트.md
    - 1기/이동근/2021-07-25-노드와-자바스크립트.md
    - 1기/이동근/2021-08-08-node-CRUD-and-간단한-머신러닝-딥러닝.md
  - 이종호:
    - 1기/이종호/2021-07-11-Introduce.md
    - 1기/이종호/2021-07-11-BasicType.md
    - 1기/이종호/2021-07-11-타입추론-타입단언.md
    - 1기/이종호/2021-07-11-redux.md
    - 1기/이종호/2021-07-18-js-oop.md
    - 1기/이종호/2021-07-18-ts-기본타입.md
    - 1기/이종호/2021-08-08-TS-refact-legacy1.md
    - 1기/이종호/2021-08-08-TS-refact-legacy2.md
  - 이태현:
    - 1기/이태현/2021-07-04-오리엔테이션-및-Git-사용법.md
    - 1기/이태현/2021-07-11-진법과-자바의-변수-메모리.md
    - 1기/이태현/2021-07-18-자바의-연산자.md
  - 이희진:
    - 1기/이희진/2021-08-08-인터넷과-프로토콜.md
  - 정선미:
    - 1기/정선미/2021-07-11-CS-객체-지향-기법.md
    - 1기/정선미/2021-07-18-Redux-Basics.md
    - 1기/정선미/2021-07-25-Redux-Basics-2.md
    - 1기/정선미/2021-08-01-redux-actions-and-immer.md
- 2기:
  - 성승익:
    - 2기/성승익/2021-09-05-내가-터미널과-친해지려는-이유.md
    - 2기/성승익/2021-09-12-grep으로-원하는-내용을-검색해보자!.md
    - 2기/성승익/2021-09-21-find로-원하는-파일을-찾아보자-1.md
    - 2기/성승익/2021-10-03-find로-원하는-파일을-찾아보자-2.md
  - 이태현:
    - 2기/이태현/2021-09-05-fastapi-and-sqlmodel-1.md
    - 2기/이태현/2021-09-14-fastapi-and-sqlmodel-2.md
    - 2기/이태현/2021-09-19-fastapi-and-sqlmodel-3.md
  - 정선미:
    - 2기/정선미/2021-09-05-javascript-01.md
    - 2기/정선미/2021-09-12-javascript-02.md
    - 2기/정선미/2021-09-20-redux-middleware-01.md
    - 2기/정선미/2021-10-03-cs-osi-7-layers.md
- 3기:
  - 구민규:
    - 3기/구민규/2021-10-30-마이크로서비스-아키텍처를-모노레포로-관리하기.md
    - 3기/구민규/2021-11-07-react에서-side-effect-관리하기.md
  - 성승익: 
    - 3기/성승익/2021-10-31-how-to-use-awk.md
  - 이태현:
    - 3기/이태현/2021-10-31-fastapi-and-sqlmodel-4.md
  - 정선미:
    - 3기/정선미/2021-10-31-useCallback-useMemo-useEffect.md

extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js      